language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run prod
before_deploy:
  - rm dist/.gitignore  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: dist
  keep-history: true
