language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run prod
before_deploy:
  - mkdir -p dist/data
  - curl -OL https://github.com/keller-mark/signature-computation/releases/download/latest-sigs/sigs.zip
  - tar -xf sigs.zip -C dist/data
  - find dist -name ".gitignore" -type f -delete
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: dist
  keep-history: true
