language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  local-dir: dist
  keep-history: true