language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  keep_history: true
